### ISSUE TITLE
Sync with official Elm version scheme

### ISSUE THREAD

**Issue by passy** [kevva/elm-platform-bin#2]
Possibly a bit late for this, but it would be nice to at least somehow surface which version of the actual Elm-Platform this corresponds to, which is 0.14 at the moment.

**Comment by passy** [comment]
I don't think it would be a problem at all if the versions were locked by default. At least until 1.0 comes around. I think `>= 0.14.0 < 0.15` should work for what @evancz suggested.

**Comment by sindresorhus** [comment]
> Say you're using ^0.1.8 or something in your package.json, if 0.1.9 is available it'll still use 0.1.8.

Nope, `^0.1.8` will install `0.1.9`, but `^0.1.8` will not install a possible `0.2.0` version.

**Comment by sindresorhus** [comment]
Syncing the version never makes sense as what happens when the bin package itself (not the elm bin) needs to do a breaking change and has to bump major.

What I would rather propose is to take advantage of the `build` specifier:

```
0.1.8+elm-1.0.0
```

Everything after the `+` is just metadata.

http://semver.org/

**Comment by kevva** [comment]
@sindresorhus, oh, yeah, they changed that, didn't they? Agree with using `+`.

**Comment by passy** [comment]
+1 for build specifier. Thanks, @sindresorhus! :)
