### ISSUE TITLE
Publish to `elm` npm repo

### ISSUE THREAD

**Issue by rtfeldman** [kevva/elm-platform-bin#4]
I know @evancz has control over https://www.npmjs.com/package/elm - which is obviously the preferred package for this, so people can just go `npm install -g elm` - which would be awesome!

**Comment by kevva** [comment]
Happy to if @evancz would like to give me ownership so I can publish :).

**Comment by sindresorhus** [comment]
@evancz, just run: `npm owner add kevva elm`

**Comment by evancz** [comment]
Okay, @kevva should be added as an owner!

I staked out that name when the main repo was still called `elm-lang/Elm` so I guess that should change to `elm-platform` or whatever is appropriate. Thanks @sindresorhus for the quick instructions :) Thanks @rtfeldman for pushing for this!

**Comment by rtfeldman** [comment]
Woo! Super excited for this! :dancer:

**Comment by kevva** [comment]
So, should I publish to `elm` or `elm-platform`?

**Comment by rtfeldman** [comment]
I would assume `elm` - the nicest syntax for installing is just `npm install -g elm`, yeah?

**Comment by evancz** [comment]
Yeah, I'd go for `elm` because in 0.15 all of the command line stuff will be routed through a command called `elm`. So instead of `elm-make` and `elm-repl` you`ll say `elm make` and `elm repl` and you can call `elm` on its own to see what your options are.

**Comment by kevva** [comment]
Alright, should be published to `elm` now.

**Comment by passy** [comment]
Woo!
