### ISSUE TITLE
What version of elm does this install?

### ISSUE THREAD

**Issue by leshow** [kevva/elm-platform-bin#5]

**Comment by shinnn** [comment]
You can see it here. https://github.com/kevva/elm-platform-bin/blob/master/package.json#L3

And related discussion: #2

**Comment by leshow** [comment]
any plans to release it for 0.15?

**Comment by kevva** [comment]
Yeah, what about #3 @passy @evancz?

**Comment by evancz** [comment]
Things seemed to be fine for 0.14.1 without #3 so I wouldn't block on that.

If you *want* to do it, give me a tarball of the things you want me to put there and tell me what they should be named. I have a flight tomorrow, and it could be a few days until I have reliable internet, so this will take some time.

**Comment by kevva** [comment]
@evancz, I just mean it would be easier if someone could build them regularly and PR them to this repo or upload somewhere, because I don't use it.
