### ISSUE TITLE
Add 0.15 binaries

### ISSUE THREAD

**Issue by rtfeldman** [kevva/elm-platform-bin#6]
I'm working on a tutorial that wants to use `npm` for installing everything, and 0.15 for Tasks, so having 0.15 available here would be great!

**Comment by passy** [comment]
I've pushed the new binaries for OS X based on the files I extracted from the official `.pkg`. For Linux I'll probably have to build them again, let's see when I can do that.

**Comment by kevva** [comment]
@passy, great :).

**Comment by kevva** [comment]
Published in https://github.com/kevva/elm-platform-bin/commit/8395c73e7852b9d541ebb31b52b72ca694f1b84b.

**Comment by rtfeldman** [comment]
Thanks for jumping on this so quickly! :heart_eyes_cat:
